apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-app
  namespace: application-test # Ensure this is the correct namespace

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bun-app
  template:
    metadata:
      labels:
        app: bun-app
    spec:
      containers:
        - name: bun-container
          image: bun-app:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: bun-service
spec:
  selector:
    app: bun-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
